### ISSUE TITLE
The dependencies are not setup correctly

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-drs-client#1]
Using the JAR from the Nexus repository will result into errors at runtime since the indirect dependencies are not configured and loaded:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/web/client/HttpClientErrorException
	at org.glygen.cfde.generator.util.CFDEGeneratorArray.getFileURLfromDRS(CFDEGeneratorArray.java:426)
	at org.glygen.cfde.generator.util.CFDEGeneratorArray.processFile(CFDEGeneratorArray.java:378)
	at org.glygen.cfde.generator.util.CFDEGeneratorArray.writeRawDataInformation(CFDEGeneratorArray.java:296)
	at org.glygen.cfde.generator.util.CFDEGeneratorArray.writeImageInformation(CFDEGeneratorArray.java:257)
	at org.glygen.cfde.generator.util.CFDEGeneratorArray.processSlideData(CFDEGeneratorArray.java:196)
	at org.glygen.cfde.generator.util.CFDEGeneratorArray.processArrayDataset(CFDEGeneratorArray.java:103)
	at org.glygen.cfde.generator.util.CFDEGeneratorArray.process(CFDEGeneratorArray.java:81)
	at org.glygen.cfde.generator.App.main(App.java:96)
	at org.glygen.cfde.generator.AppRun.main(AppRun.java:11)
Caused by: java.lang.ClassNotFoundException: org.springframework.web.client.HttpClientErrorException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 9 more

```
The line that causes this is:
```
DRSClient t_drsClient = new DRSClientImpl();
```
It can not find the spring web client stuff. It was probably fine for you since you had it in your workspace/project. If the spring web client requires a lot of other dependencies I think it might be better to use something with a flatter dependency hierarchy instead (e.g. 
```
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
      <version>4.5.13</version>
    </dependency>
```

**Comment by senaarpinar** [comment]
updated the jar file to include the dependencies. @ReneRanzinger can you test again?

**Comment by ReneRanzinger** [comment]
Its still not working even when using 1.0.1

![Screenshot_20230911_183531](https://github.com/glygener/glygen-drs-client/assets/2267640/cdf18561-0877-4e04-8708-884d6fe66d0c)

In the Maven Dependencies in only see the client no spring stuff. Also in the jar is nothing besides your code. The POM file in the jar has the dependencies but the POM file on the [top level of the repository](https://glygen.ccrc.uga.edu/repository/content/repositories/thirdparty/org/glygen/drsclient/1.0.1/) does not. I was reading that the standard method for deploying to a repository should be `mvn deploy` (correctly configured). Have you tried this?

**Comment by ReneRanzinger** [comment]
Loading with the POM file fixed it.
